config/routes.rb
Rails.application.routes.draw do
  resources :applications
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :jobs
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
      cannot :create, Application
      cannot :destroy, Application
      cannot :destroy, User
    else
      can :read, Job
      can :read, Application, user: user
      can :update, Application, user: user
      can :destroy, Application, user: user
      can :create, Application
      cannot :destroy, Job
      cannot :create, Job
      cannot :update, Job
    end
  end
end

app/models/application.rb
class Application < ApplicationRecord
  STATUS_OPTIONS = ['Seen', 'Not Seen']
  
  belongs_to :user
  belongs_to :job

  validates_uniqueness_of :job_id, scope: :user_id
  validates_inclusion_of :status, in: STATUS_OPTIONS

  validate do
    if user.admin?
      errors.add(:application, "Admin can not create applications")
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  searchkick word_middle: [:title, :description]

  has_many :applications, dependent: :destroy
  belongs_to :user
  
  validates :title, :description, presence: true

  after_save do
    Job.reindex
  end

  validate do
    if !user.admin?
      errors.add(:user, "Only admins can create a job")
    end
  end

  def search_data
    {
      title: title,
      description: description
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :applications, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validate do 
    if self.admin == true && User.exists?(admin: true)
      errors.add(:admin, "there can only be one admin")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  skip_before_action :verify_authenticity_token, if: :json_request?

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { render json: {error: "You do not have access to this action"}, status: :forbidden }
      format.html { redirect_to root_url, notice: exception.message, status: :forbidden }
      format.js   { render nothing: true, status: :forbidden }
    end
  end

  rescue_from(
    ActionController::RoutingError,
    ActionController::ParameterMissing,
    ActiveRecord::RecordNotFound) do |exception|
    respond_to do |format|
      format.json { render json: { error: exception.message }, status: :bad_request }
      format.html { redirect_to root_url, notice: exception.message, status: :bad_request }
      format.js   { render nothing: true, status: :bad_request }
    end
  end

  protected
    def json_request?
      request.format.json?
    end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_application, only: [:show, :destroy]
  before_action :set_application_as_seen, only: [:show]
  
  load_and_authorize_resource

  # GET /applications or /applications.json
  def index
    @applications = Application.accessible_by(current_ability)
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @applications}
      format.json { render json: {applications: @applications}}
    end
  end

  # GET /applications/1 or /applications/1.json
  def show
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @application}
      format.json { render json: {application: @application}}
    end
  end

  # POST /applications or /applications.json
  def create
    @application = Application.new(application_params)

    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: "Application was successfully created." }
        format.json { render :show, status: :created, location: @application }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1 or /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url, notice: "Application was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    def set_application_as_seen
      if current_user.admin? && @application.status == 'Not Seen'
        @application.assign_attributes(status: 'Seen')
        render json: @application.errors, status: :unprocessable_entity if !@application.save
      end
    end

    # Only allow a list of trusted parameters through.
    def application_params
      params.require(:application).permit(:user_id, :job_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource

  # GET /jobs or /jobs.json
  def index
    search = params[:search]
    if !search.blank?
      @jobs = Job.search(search)
      # Filtering on search kept not returning anything, so I commented it
      # @jobs = Job.search(search, where: {expiry_date: {gt: DateTime.now}})
    else
      @jobs = Job.where('expiry_date > ?', DateTime.now)
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @jobs}
      format.json { render json: {jobs: @jobs}}
    end
  end

  # GET /jobs/1 or /jobs/1.json
  def show
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @job}
      format.json { render json: @job}
    end
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params.merge({user_id: current_user.id}))

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:title, :description, :expiry_date)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
   def sign_up_params
      params.require(:user).permit(:email, :password, :password_confirmation, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/applications/index.html.erb
<h1>Applications</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>User</th>
      <th>Job</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= application.status %></td>
        <td><%= application.user_id %></td>
        <td><%= application.job_id %></td>
        <td><%= link_to 'Show', application %></td>
        <% if can? :destroy, @application %>
          <td><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/applications/show.html.erb
<p>
  <strong>Status:</strong>
  <%= @application.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @application.user_id %>
</p>

<p>
  <strong>Job:</strong>
  <%= @application.job_id %>
</p>

<%= link_to 'Back', applications_path %>

app/views/home/_footer.html.erb
<footer class='fixed-bottom text-end py-2 px-3'>
  <% if user_signed_in? %>
  <strong>Logged In User: </strong>
  <%= current_user.email %>
  <% end %>
</footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'JobsTask', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to 'List Jobs', jobs_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Add Jobs', new_job_path, class: 'nav-link' %>
        </li>
        <% unless user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <%= text_field_tag :search, params[:search], class: "form-control me-2", placeholder: "Search", autocomplete: "off" %>
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<div>This is the home page</div>

app/views/jobs/_form.html.erb
<%= form_with(model: job) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :expiry_date %>
    <%= date_field("job", "expiry_date") %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<h1>Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.description %></td>
        <td><%= link_to 'Show', job %></td>
        <% if can? :update, @job %>
          <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <% end %>
        <% if can? :destroy, @job %>
          <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :create, Job %>
  <%= link_to 'New Job', new_job_path %>
<% end %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Expiry Date:</strong>
  <%= @job.expiry_date %>
</p>

<% if user_signed_in? and can? :create, Application %>
<%= button_to 'Apply', applications_path, 
    method: :post, 
    params: { application: {user_id: current_user.id, job_id: @job.id} }, 
    class: "btn btn-dark" 
%>
<% end %>

<% if can? :update, @job %>
<%= link_to 'Edit', edit_job_path(@job) %> |
<% end %>
<%= link_to 'Back', jobs_path %>

app/views/layouts/_alerts.html.erb
<% if notice %>
<p class="notice"><%= notice %></p>
<% end %>
<% if alert %>
<p class="alert"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobsAPI</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/header' %>
    <%= render 'layouts/alerts' %>
    <div class='container mt-3'>
      <%= yield %>
    </div>
    <%= render 'home/footer' %>
  </body>
</html>